# Generated by Django 4.1 on 2025-12-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genre",
            new_name="genres",
        ),
    ]
