# Generated by Django 4.1 on 2025-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_rename_genre_movie_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, to="cinema.genre"),
        ),
    ]
