# Generated by Django 4.1 on 2025-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_remove_movie_genres_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="movies", to="cinema.genre"
            ),
        ),
    ]
